"""
Business logic for child profile management.
"""
import uuid
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from api.children import schemas
from db.models import AuditLog, Child


async def get_children(parent_id: uuid.UUID, db: AsyncSession) -> list[Child]:
    """
    Retrieve all children profiles registered to a given parent.

    Args:
        parent_id: UUID of the parent user.
        db: Async database session.

    Returns:
        List of Child database models.
    """
    result = await db.execute(
        select(Child)
        .where(Child.parent_id == parent_id)
        .order_by(Child.created_at.desc())
    )
    return list(result.scalars().all())


async def create_child(
    parent_id: uuid.UUID,
    payload: schemas.ChildCreateRequest,
    db: AsyncSession,
) -> Child:
    """
    Register a new child profile for a parent.

    Args:
        parent_id: UUID of the registering parent.
        payload: Child registration details.
        db: Async database session.

    Returns:
        The created Child database model.
    """
    child = Child(
        parent_id=parent_id,
        name=payload.name,
        date_of_birth=payload.date_of_birth,
        gender=payload.gender,
        notes=payload.notes,
    )
    db.add(child)
    await db.flush()  # Obtain the child.id generated by database

    # Write audit log
    audit = AuditLog(
        user_id=parent_id,
        action="CHILD_CREATED",
        resource_type="Child",
        resource_id=str(child.id),
    )
    db.add(audit)
    await db.flush()

    return child
